refactor: Improve communication between plugin and ui & bundle ui
treymo/joplin-link-graph pull request #36
Opened 2021-09-23 14:13 UTC by agerardin

The plugin is relying on a timer that triggers a full refresh every second.
This impacts UI responsiveness and increase resource usage.
The UI script also uses a timer to figure out when the d3 library has finished loading.

This commit addresses both issues by:

* Replacing the first timer by a poll mechanism. When the API notifies
  on a change, a model change is added to a queue. The ui checks the queue
  for new updates and apply them. This allows for a cleaner execution model
  and improves responsiveness.

* Using extra-scripts to bundle ui & d3 with webpack. This removes the
  second timer and have the side benefit of reducing the plugin's size by
  5 due to treeshaking.

2021-09-24 21:54 UTC, treymo commented
Thank you for this @agerardin!! I'll review this today or tomorrow and get it merged

2021-09-24 22:15 UTC, treymo commented
I'm testing this out locally and seeing: `Module not found: Error: Can't resolve 'd3' in '$HOME/dev/joplin-graph-view/src/ui'`

I think the d3.js file should remain checked into the repo.  Are you installing that dependency somewhere outside the repository on your machine?

2021-09-24 22:17 UTC, treymo requested changes
I'm testing this out locally and seeing: `Module not found: Error: Can't resolve 'd3' in '$HOME/dev/joplin-graph-view/src/ui'`

I think the d3.js file should remain checked into the repo. Are you installing that dependency somewhere outside the repository on your machine?

2021-09-25 13:52 UTC, agerardin commented
Hello! I have added d3 as a dependency in ```package.json```.  ```ui/index.js``` is declared as an extraScript in ```plugin.config.json``` so it will be bundled by webpack in a separate entry. rerun ```npm install``` should get rid of the error.

2021-09-28 19:38 UTC, treymo commented on src/index.ts
> +async function redraw() {
Is this function used, if not, please remove

2021-09-28 19:43 UTC, treymo commented on src/index.ts
> +  const selectedFolder = await joplin.workspace.selectedFolder();
Is this used?

2021-09-28 19:48 UTC, treymo requested changes
Just a couple minor questions, but this is a great improvement! Thank you for bringing some real JS experience to the project haha

2021-10-02 13:40 UTC, agerardin commented
Hello! I have updated with your remarks. 
The promise callback mechanism is still quite hacky but that's the best I could come out with using the current webviewAPI. I am delving into Joplin's plugin code to see how to do better  but it will take some more time.

2021-10-02 16:38 UTC, treymo approved these changes

2021-10-02 16:38 UTC, merged

2021-10-06 17:07 UTC, agerardin commented
To follow up on this, I was looking for a mechanism to send message from the plugin to the view rather than polling the plugin for changes. This is currently not implemented. I have a pull request ready for enabling push notifications so I will start discussing it with Joplin's contributors. Until this happens, the current method will do!